### ISSUE TITLE
Generate openssh client policies

### ISSUE THREAD

**Issue by nmav** [nmav/fedora-crypto-policies#7]
After F26 we will be able to include policies for the OpenSSH client. These will cover the following configuration options:
 * Ciphers, KexAlgorithms, MACs
 * GSSAPIKexAlgorithms
 * HostKeyAlgorithms, PubkeyAcceptedKeyTypes

**Comment by Jakuje** [comment]
This was solved by the pull #8 (the scope without the key types)
